Refactor notification Component
chain4travel/camino-suite pull request #127
Opened 2023-06-05 07:36 UTC by aeddaqqa

adjust the component of notifications to have the title in props and can be displayed in the Snackbar if needed

2023-06-09 21:05 UTC, Esteban100k approved these changes

2023-06-20 09:35 UTC, Ayagoumi requested changes

2023-06-20 09:35 UTC, Ayagoumi commented on src/components/Notification.tsx
> +                            padding: '6px 16px',
what's the reasoning for adding this padding?

2023-06-20 09:35 UTC, Ayagoumi commented on src/components/Notification.tsx
> +                            border: '1px solid rgba(145, 158, 171, 0.24)',
this makes it different from what we have in the BE

2025-04-10 08:07 UTC, closed without merging