feat(Partners): enhance BusinessFieldFilter with grouped display
chain4travel/camino-suite pull request #266
Opened 2024-11-04 09:16 UTC by Ysrbolles

Extending the business field values to hold both a category and the business field itself. Something like:

* Transport / Train
* Transport / Aviation
* Accommodation / Hotel
* Accommodation / Holiday-Home
* etc

With the purpose to show this in the frontend grouped by the first field like "Transport" "Accommodation" and have the 2nd part as selectable filter criteria to search for businesses which have for instance "Transport / Train" selected.

<img width="1173" alt="Screenshot 2024-11-04 at 10 15 29" src="https://github.com/user-attachments/assets/ce6ed2fe-756c-47da-94f6-97a492a5cf0f">

2024-11-05 11:30 UTC, aeddaqqa requested changes

2024-11-05 11:30 UTC, aeddaqqa commented on src/components/Partners/BusinessFieldFilter.tsx
> +        console.log(event.target.value);
remove iff the console is not needed

2024-11-05 11:30 UTC, aeddaqqa commented on src/components/Partners/BusinessFieldFilter.tsx
> +            {groupedBusinessFields.flatMap((group, groupIndex) => [
The business fields should be grouped by the first element of each business field, not by the complete name

2024-11-05 11:30 UTC, aeddaqqa commented on src/helpers/partnersReducer.ts
> +            console.log('action', [...state.businessField])
console not needed

2024-11-05 11:30 UTC, aeddaqqa commented on src/helpers/partnersReducer.ts
>              let newBusinessField = [...state.businessField]
Perhaps the grouping should be done when initializing the state with the grouped business fields. This way, they can also be used in other parts, such as the partner view, where we may want to group them as well

2024-11-05 13:54 UTC, Ysrbolles commented on src/helpers/partnersReducer.ts
>              let newBusinessField = [...state.businessField]
I'll check that, thank you

2024-11-05 13:59 UTC, Ysrbolles commented on src/components/Partners/BusinessFieldFilter.tsx
> +            {groupedBusinessFields.flatMap((group, groupIndex) => [
Yes, that's what happened, it’s split by `/` because it will come from Strapi in this format: `Transport / Train`

2024-11-11 08:54 UTC, aeddaqqa approved these changes

2024-11-11 09:06 UTC, Ysrbolles commented
feat(BusinessFieldFilter): add category-level toggling for business fields

- Made category headers clickable, allowing users to toggle the active state of all fields within a category in the BusinessFieldFilter component.
- Updated reducer with a new action `TOGGLE_CATEGORY` to handle toggling all fields in the selected category when the header is clicked.
- Preserved the existing styles for category headers and individual fields.

This update improves usability by enabling easier selection of grouped business fields.

2024-11-11 09:06 UTC, merged