fix updating utxos multiple times
chain4travel/camino-suite pull request #75
Opened 2023-02-21 14:57 UTC by aeddaqqa

this PR is for fixing and updating the UTXOs after the network is changed

2023-02-21 15:51 UTC, Ayagoumi requested changes

2023-02-21 15:51 UTC, Ayagoumi commented on src/components/Navbar/NetworkSwitcher.tsx
>  import React, { useEffect } from 'react'
Remove unused useEffect

2023-02-24 08:48 UTC, Chriserus approved these changes, later dismissed

2023-02-24 12:18 UTC, Ayagoumi submitted a review, later dismissed
Looks Good. 

@aeddaqqa resolve merge conflicts

2023-02-24 12:51 UTC, Ayagoumi approved these changes

2023-02-24 13:03 UTC, Chriserus approved these changes

2023-02-24 13:27 UTC, merged