fix login issues and add create component
chain4travel/camino-suite pull request #9
Opened 2022-12-19 09:17 UTC by aeddaqqa

- fix login with mnemoniac phrase issue 
- fix login options lead back to the wallet starting page
- add create wallet process to camino suite application

2022-12-19 14:51 UTC, Ayagoumi requested changes
remove unnecessary comments

2022-12-19 14:51 UTC, Ayagoumi commented on wallet/src/views/access/Mnemonic.vue
> +        // let parent = this
unnecessary comment, please remove it.

2022-12-19 17:25 UTC, Ayagoumi approved these changes

2022-12-19 18:01 UTC, Chriserus approved these changes
Small comments, otherwise LGTM

2022-12-19 18:01 UTC, Chriserus commented on wallet/src/views/Create.vue
> +    /*grid-template-columns: 1fr 1fr;*/
Unnecessary comments

2022-12-19 18:01 UTC, Chriserus commented on wallet/src/views/Create.vue
> +                    content: 'Create | Avalanche Wallet',
Please rebrand to Camino Wallet

2022-12-19 18:01 UTC, Chriserus commented on wallet/src/views/Create.vue
> +            "Here at Avalanche, we've made storing digital assets easy. Create an Avalanche wallet today is see what the buzz is all about!"
Please rebrand to Camino Wallet

2022-12-20 07:33 UTC, Chriserus approved these changes

2022-12-20 09:05 UTC, merged